"""alterando agendamentos: removendo default da coluna hour

Revision ID: 0cf42dd4b053
Revises: 199bba78dcb4
Create Date: 2025-09-05 15:29:11.410786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf42dd4b053'
down_revision: Union[str, Sequence[str], None] = '199bba78dcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
