"""tornando agendamentos.hour único e agendamentos.is_free nullable=false

Revision ID: 15ff4b9036e0
Revises: afd99d522514
Create Date: 2025-09-10 20:07:03.778523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ff4b9036e0'
down_revision: Union[str, Sequence[str], None] = 'afd99d522514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'agendamentos', ['hour'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agendamentos', type_='unique')
    # ### end Alembic commands ###
