"""alterando agendamentos: add column is_free

Revision ID: 199bba78dcb4
Revises: 63ce87a203f2
Create Date: 2025-09-05 15:27:24.858938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199bba78dcb4'
down_revision: Union[str, Sequence[str], None] = '63ce87a203f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('is_free', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendamentos', 'is_free')
    # ### end Alembic commands ###
