"""adicionando campo status a tabela agendamentos

Revision ID: afcbca4a10df
Revises: bd56c644b1d1
Create Date: 2025-09-16 14:18:24.067380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afcbca4a10df'
down_revision: Union[str, Sequence[str], None] = 'bd56c644b1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('status', sa.Enum('FREE', 'REQUESTED', 'CONFIRMED', name='appointmentstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendamentos', 'status')
    # ### end Alembic commands ###
