"""tornando agendamentos.hour não nulo

Revision ID: afd99d522514
Revises: ee0bcb7fe67e
Create Date: 2025-09-07 13:31:31.932444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'afd99d522514'
down_revision: Union[str, Sequence[str], None] = 'ee0bcb7fe67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agendamentos', 'hour',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agendamentos', 'hour',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
