"""tornando default de agendamentos.is_free em True

Revision ID: bd56c644b1d1
Revises: 15ff4b9036e0
Create Date: 2025-09-11 17:33:08.767449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd56c644b1d1'
down_revision: Union[str, Sequence[str], None] = '15ff4b9036e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
