"""adicionando tabela admin

Revision ID: d6a8635ba098
Revises: e50b3467fa7d
Create Date: 2025-09-23 18:04:18.288455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd6a8635ba098'
down_revision: Union[str, Sequence[str], None] = 'e50b3467fa7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.alter_column('agendamentos', 'status',
               existing_type=mysql.ENUM('FREE', 'REQUESTED', 'CONFIRMED', 'RESERVED'),
               type_=sa.Enum('FREE', 'RESERVED', 'REQUESTED', 'CONFIRMED', name='appointmentstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agendamentos', 'status',
               existing_type=sa.Enum('FREE', 'RESERVED', 'REQUESTED', 'CONFIRMED', name='appointmentstatus'),
               type_=mysql.ENUM('FREE', 'REQUESTED', 'CONFIRMED', 'RESERVED'),
               existing_nullable=False)
    op.drop_table('admin')
    # ### end Alembic commands ###
