"""tornando clientes.chat_id unique = true

Revision ID: ee0bcb7fe67e
Revises: f608acd0a115
Create Date: 2025-09-06 11:00:13.450967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0bcb7fe67e'
down_revision: Union[str, Sequence[str], None] = 'f608acd0a115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'clientes', ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='unique')
    # ### end Alembic commands ###
